name: eazimeet

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout respository
              uses: actions/setup-node@v4
              with:
                node-version: 20.16.0
            
            - name: Install dependencies
              run: npm install
            
            - name: Run tests
              run: npm test

            - name: Build project
              run: npm run build